### PR TITLE
Ensure consisteny response for all types

### PR DESCRIPTION
**Pull request by josharsh**
## What are the changes introduced in this PR?
Brings consistency to response for array inputs with a single item.

Before this change, 
```
const engine = JsonTemplateEngine.create(`^.orders@order.products@product.({
    product_name: product.name
  })`)

let input = {
    "orders": [
      {
        "products": [
          {
            "name": "Smartphone"
          }
        ]
      },
      {
        "products": []
      }
    ]
  }
let output = engine.evaluate(input).then((result) => {console.log(result)});
```

was resulting into 
```json
{"product_name" : "Smartphone"} 
```

Whereas, for the same template input array with multiple items was returning the following response -
```js
const engine = JsonTemplateEngine.create(`^.orders@order.products@product.({
    product_name: product.name
  })`)
  
let input = {
    "orders": [
      {
        "products": [
          {
            "name": "Smartphone"
          }
        ]
      },
      {
        "products": [
          {
            "name": "Laptop"
          },
          {
            "name": "Headphones"
          }
        ]
      }
    ]
  }
let output = engine.evaluate(input).then((result) => {console.log(result)});
```
Response
```json
[
  {
    "product_name": "Smartphone"
  },
  {
    "product_name": "Laptop"
  },
  {
    "product_name": "Headphones"
  }
]
```
Write a brief explainer on your code changes.
* Added a minor condition that always converts response to array.

## What is the related Linear task?
N/A
Resolves INT-XXX

## Please explain the objectives of your changes below
* When this library is used on production, consistent response format helps avoid edge cases

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### Any technical or performance related pointers to consider with the change?

N/A

@coderabbitai review

<hr>

### Developer checklist

- [ x ] My code follows the style guidelines of this project

- [ x ] **No breaking changes are being introduced.**

- [ x ] All related docs linked with the PR?

- [ x ] All changes manually tested?

- [ x ] Any documentation changes needed with this change?

- [ x ] Is the PR limited to 10 file changes?

- [ x ] Is the PR limited to one linear task?

- [ x ] Are relevant unit and component test-cases added?

### Reviewer checklist

- [ ] Is the type of change in the PR title appropriate as per the changes?

- [ ] Verified that there are no credentials or confidential data exposed with the changes.

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved stability by ensuring the `dest` variable is correctly converted to an array if it is not already one. This prevents potential errors in translation templates.

### CODE REVIEW

**Comment by koladilip** [comment]
we convert a single element array to an element, if you want to return an array always then use following template: 
```js
`^.orders@order.products@product.({
    product_name: product.name
  }[]
```
refer: https://transformers-workflow-engine.rudderstack.com/#/json-template?gist=76329f8abe706e111ce176e5f0a39266

**Comment by josharsh** [comment]
Please help with this case

```
let input = {
    "orders": [
      {
        "products": [
          {
            "name": "Smartphone"
          }
        ]
      },
      {
        "products": []
      }
    ]
  }
```
Expected Response -
```
[ { product_name: 'Smartphone' } ]
```

```
let input2 = {
    "orders": [
      {
        "products": [
          {
            "name": "Smartphone"
          }
        ]
      },
      {
        "products": [
          {
            "name": "Laptop"
          },
          {
            "name": "Headphones"
          }
        ]
      }
    ]
  }
```

expected response
```json
[
  { product_name: 'Smartphone' },
  { product_name: 'Laptop' },
  { product_name: 'Headphones' }
]
```



Right now only one of the two works at a time, how can I solve it generically because I don't control the input here.

**Comment by koladilip** [comment]
refer: https://transformers-workflow-engine.rudderstack.com/#/json-template?gist=55bb3ecf0ca1ead29e39e80fde24db79
and 
 https://transformers-workflow-engine.rudderstack.com/#/json-template?gist=76329f8abe706e111ce176e5f0a39266
 
you can achieve this by
```js
^.orders@order.products@product.({
    product_name: product.name
  }[]
```

**Comment by koladilip** [comment]
@josharsh is your issue addressed?

**Comment by koladilip** [comment]
this is not required

**Pull request closed without merging**
